<?php

namespace cc\relationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdinateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdinateurRepository extends EntityRepository
{
    
     public function findByLibelle($lib){
        $qb = $this->createQueryBuilder('o');
        $qb->where('o.libelleOrdi = :lib')->setParameter('lib', $lib);
        
        return $qb->getQuery()->getSingleResult();
    }
    
}
