<?php

namespace cc\relationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarieRepository extends EntityRepository
{
    
    public function findByName($nom){
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.nomSalarie = :nom')->setParameter('nom', $nom);
        
        return $qb->getQuery()->getSingleResult();
    }
    
    public function findByOrdi($ordi){
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.ordinateur = :ordi')->setParameter('ordi', $ordi);
        
        return $qb->getQuery()->getSingleResult();
    }
}
